Add optional "billing unit" to customer invoice
HubTran/documentation pull request #93
Opened 2020-09-16 17:40 UTC by kaleposhobios

2020-09-16 18:15 UTC, r38y commented on brokers/rest.md
> +    "billing_unit": {                                  // Optional, if this invoice belongs to a specific billing unit inside your account.
Billing unit or business unit?

2020-09-16 18:34 UTC, r38y requested changes

2020-09-16 18:34 UTC, r38y commented on brokers/rest.md
> +      "name": "example-name"                           // Optional, recommended if new billing unit
I'd make name required here and in the model since just external_id doesn't really do anything for us.

2020-09-16 18:42 UTC, kaleposhobios commented on brokers/rest.md
> +      "name": "example-name"                           // Optional, recommended if new billing unit
Thanks!

2020-09-16 19:52 UTC, r38y approved these changes

2020-09-22 19:12 UTC, r38y approved these changes

2020-11-09 16:41 UTC, kaleposhobios reviewed
Ok!

2020-11-11 15:36 UTC, merged